linters:
  enable:
    - errorlint
    - exhaustive
    - goconst
    - godot
    - goimports
    - goprintffuncname
    - ifshort
    - makezero
    - nilerr
    - prealloc
    - thelper
    - unconvert
    - unparam
    - wastedassign
